// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
}

type Post struct {
	ID          int64
	Title       string
	Description string
	CreatedAt   sql.NullTime
	AuthorID    int64
}
