// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Post struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	AuthorID    int64        `json:"author_id"`
}
